### ISSUE TITLE
[feature] Can I make a 2x2x4 sudoku game with fill=1, count=4? How?

### ISSUE THREAD

**Issue by thelou1s** [forfuns/sudoku-dart#1]

**Comment by einsitang** [comment]
sorry,I don't understand what is `2 x 2 x 4` sudoku ?

**Comment by einsitang** [comment]
<img width="622" alt="image" src="https://user-images.githubusercontent.com/1745525/183854546-f5c88514-b6e0-4758-9cc8-ccaca3d248cc.png">

is that what your mean ?

**Comment by thelou1s** [comment]
yes :)

**Comment by einsitang** [comment]
> yes :)

`sudoku-dart` is not support custom row and col mode , but u can change hard code to make it work, only code on `/lib `folder,and is all the magic code (because I never thought this feature to support)
