### ISSUE TITLE
tools中的Matrix.getIndex计算错误

### ISSUE THREAD

**Issue by wilhantian** [forfuns/sudoku-dart#2]
原 `static int getIndex(int row, int col) => col * 9 + row;`
应该改为 `static int getIndex(int row, int col) => row * 9 + col;`

库中虽未使用`Matrix.getIndex`函数，但可能对其他开发者带来困扰

这是很好的dart库 🎉

**Comment by einsitang** [comment]
感谢反馈，已修改
